[project]
name = "life365-search"
version = "0.1.0"
description = "Searching Life365 products"
authors = [
    {name = "Luca Bacchi",email = "bacchilu@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4"

[tool.pytest.ini_options]
pythonpath = ["."]
